-- MySQL Script generated by MySQL Workbench
-- Tue Mar 26 13:47:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CDO
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CDO` ;

-- -----------------------------------------------------
-- Schema CDO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CDO` DEFAULT CHARACTER SET utf8 ;
USE `CDO` ;

-- -----------------------------------------------------
-- Table `CDO`.`Общеобразовательное направление`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CDO`.`Общеобразовательное направление` ;

CREATE TABLE IF NOT EXISTS `CDO`.`Общеобразовательное направление` (
  `id` INT NOT NULL,
  `ChildSurname` VARCHAR(45) NOT NULL COMMENT 'Фамилия ребенка',
  `ChildName` VARCHAR(45) NOT NULL COMMENT 'Имя ребенка',
  `ChildPatronymic` VARCHAR(45) NOT NULL COMMENT 'Отчество ребенка',
  `ChildBirthDate` DATETIME NOT NULL COMMENT 'Дата рождения',
  `Pasport` VARCHAR(45) NOT NULL COMMENT 'Серия и номер паспорта',
  `PhoneNumber` VARCHAR(45) NOT NULL COMMENT 'Номер телефона',
  `ProgramName` VARCHAR(45) NOT NULL COMMENT 'Название программы',
  `ProgramCost` DECIMAL UNSIGNED NOT NULL COMMENT 'Стоимость программы',
  `DisciplineTime` INT NOT NULL COMMENT 'Объем диципилны(время)',
  `OrderNumber` INT NOT NULL COMMENT 'Номер приказа',
  `ParentSurname` VARCHAR(45) NOT NULL COMMENT 'Фамилия родителя',
  `ParentName` VARCHAR(45) NOT NULL COMMENT 'Имя родителя',
  `ParentPatronymic` VARCHAR(45) NOT NULL COMMENT 'Отчество родителя',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `PhoneNumber_UNIQUE` (`PhoneNumber` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CDO`.`Повышение квалификации`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CDO`.`Повышение квалификации` ;

CREATE TABLE IF NOT EXISTS `CDO`.`Повышение квалификации` (
  `id` INT NOT NULL,
  `ClientSurname` VARCHAR(45) NOT NULL COMMENT 'Фамилия заказчика',
  `ClientName` VARCHAR(45) NOT NULL COMMENT 'Имя заказчика',
  `ClientPatronymic` VARCHAR(45) NOT NULL COMMENT 'Отчество заказчика',
  `ClientBirthDate` DATETIME NOT NULL COMMENT 'Дата рождения заказчика',
  `Pasport` VARCHAR(45) NOT NULL COMMENT 'Серия и номер паспорта',
  `PhoneNumber` VARCHAR(45) NOT NULL COMMENT 'Номер телефона',
  `ProgramName` VARCHAR(45) NOT NULL COMMENT 'Название программы',
  `DisciplineTime` INT NOT NULL,
  `ProgramCost` INT UNSIGNED NOT NULL COMMENT 'Количество часов ',
  `ApplicationDate` DATETIME NOT NULL COMMENT 'Дата подачи заявления',
  `AdmissionReason` VARCHAR(45) NOT NULL COMMENT 'Основание зачисления',
  `EnrollmentDate` DATETIME NOT NULL,
  `DeductionDate` DATETIME NOT NULL COMMENT 'Дата отчисления',
  `DeductionReason` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CDO`.`Программа проф переподготовки`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CDO`.`Программа проф переподготовки` ;

CREATE TABLE IF NOT EXISTS `CDO`.`Программа проф переподготовки` (
  `id` INT NOT NULL,
  `ClientSurname` VARCHAR(45) NOT NULL COMMENT 'Фамилия заказчика',
  `ClientName` VARCHAR(45) NOT NULL COMMENT 'Имя заказчика',
  `ClientPatronymic` VARCHAR(45) NOT NULL COMMENT 'Отчество заказчика',
  `Address` VARCHAR(45) NOT NULL COMMENT 'Адрес',
  `Pasport` VARCHAR(45) NOT NULL COMMENT 'Серия и номер паспорта',
  `PhoneNumber` VARCHAR(45) NOT NULL COMMENT 'Номер телефона',
  `ProgramName` VARCHAR(45) NOT NULL COMMENT 'название программы',
  `ProgramCost` DECIMAL NOT NULL COMMENT 'Стоимость программы',
  `AgreementDate` DATETIME NOT NULL COMMENT 'Дата договора',
  `DisciplineName` VARCHAR(45) NOT NULL COMMENT 'Название дисциплины',
  `DisciplineTime` INT NOT NULL COMMENT 'Объем дисциплины(кол-во часов)',
  `Examiner` VARCHAR(45) NOT NULL COMMENT 'Экзаменатор',
  `TestDate` DATETIME NOT NULL COMMENT 'Дата зачета',
  `Rating` VARCHAR(45) NOT NULL COMMENT 'Оценка',
  `FinalTestDate` DATETIME NOT NULL COMMENT 'Дата допуска к итоговой аттестации',
  `ReasonFinalTest` VARCHAR(45) NOT NULL COMMENT 'Основание допуска к итоговой аттестации',
  `ComissionDate` DATETIME NOT NULL COMMENT 'Дата утверждерждения состава комисии',
  `DeductionDate` DATETIME NOT NULL COMMENT 'Дата отчисления',
  `DeductionReason` VARCHAR(45) NOT NULL COMMENT 'Основание отчисления',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
